-- MySQL Script generated by MySQL Workbench
-- Sun Jun 16 17:07:31 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema airCompany
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema airCompany
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `airCompany` DEFAULT CHARACTER SET utf8 ;
USE `airCompany` ;

-- -----------------------------------------------------
-- Table `airCompany`.`aircraft`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airCompany`.`aircraft` ;

CREATE TABLE IF NOT EXISTS `airCompany`.`aircraft` (
  `idaircraft` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idaircraft`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airCompany`.`airplain`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airCompany`.`airplain` ;

CREATE TABLE IF NOT EXISTS `airCompany`.`airplain` (
  `idairplain` INT NOT NULL,
  `model` VARCHAR(45) NULL,
  `speed` INT NULL,
  `weight` DOUBLE NULL,
  `people_capasity` INT NULL,
  `rangeOfFlight` INT NULL,
  `aircraftid` INT NULL,
  PRIMARY KEY (`idairplain`),
  INDEX `air_idx` (`aircraftid` ASC) VISIBLE,
  CONSTRAINT `air`
    FOREIGN KEY (`aircraftid`)
    REFERENCES `airCompany`.`aircraft` (`idaircraft`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `airCompany`.`aircraft`
-- -----------------------------------------------------
START TRANSACTION;
USE `airCompany`;
INSERT INTO `airCompany`.`aircraft` (`idaircraft`, `name`) VALUES (1, 'belavia');

COMMIT;


-- -----------------------------------------------------
-- Data for table `airCompany`.`airplain`
-- -----------------------------------------------------
START TRANSACTION;
USE `airCompany`;
INSERT INTO `airCompany`.`airplain` (`idairplain`, `model`, `speed`, `weight`, `people_capasity`, `rangeOfFlight`, `aircraftid`) VALUES (1, '737-400', 807, 62823, 168, 3815, 1);
INSERT INTO `airCompany`.`airplain` (`idairplain`, `model`, `speed`, `weight`, `people_capasity`, `rangeOfFlight`, `aircraftid`) VALUES (2, '737-800', 852, 79015, 189, 5765, 1);
INSERT INTO `airCompany`.`airplain` (`idairplain`, `model`, `speed`, `weight`, `people_capasity`, `rangeOfFlight`, `aircraftid`) VALUES (3, '737-900ER', 852, 74389, 215, 5925, 1);

COMMIT;

